version: '3'
services:
  frontend:
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true
  api:
    restart: always
    build: ./backend
    ports:
      - '5050:5050'
    volumes:
      - ./backend:/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo

volumes:
  mongodb_data: