version: '3'

services:
  frontend:
    tty: true 
    #restart: always
    build: .
    ports:
       - '3000:3000'
    #volumes:
     # - /node_modules
      # make sure i add persistent later
    #environment
  redis: 
    image: redis
    ports:
      - '6379:6379'
    volumes:
       - type: volume
         source: redis_data
         target: server/instance/db.sqlite
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment: 
      - REDIS_HOSTS=local:redis:6379
    ports: 
      - "8081:8081"
    depends_on: 
      - redis
  backend:
    tty: true 
    # restart: always
    # command: ["pip", "install",  "python-dotenv"]
    
    build: ./server
    ports:
     - "8000:8000"

volumes:
  redis_data: