# version: '3'

# services:
#   frontend:
#     tty: true
#     build: 
#       context: ./frontend
#     ports:
#        - '3000:3000'

#   redis:
#     image: redis
#     ports:
#       - "6379:6379"

#   backend:
#     build:
#       context: ./server  # Adjust the context to point to your backend directory
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     depends_on:
#       - redis
#     volumes:
#       - ./server/instance:/backend/instance  # Mount SQLite database volume

version: '3'

services:
  frontend:
    build: 
      context: ./frontend
    tty: true
    environment:
      - PORT=8080   # Ensure your frontend listens on this port for Cloud Run
    ports:
      - '3000:3000' # Map local port for development; remove this for Cloud Run

  redis:
    image: redis
    ports:
      - "6379:6379" # Map local port for development; can be removed if using Memorystore

  backend:
    build:
      context: ./server  # Adjust the context to point to your backend directory
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - redis  # If using Redis in Cloud Run; change this if using Memorystore
    volumes:
      - ./server/instance:/backend/instance  # Mount SQLite database volume
    environment:
      - PORT=8080  # Ensure your backend listens on this port for Cloud Run
      - REDIS_URL=redis://localhost:6379  # Update to your Redis URL for production
