version: '3'

services:
  frontend:
    tty: true 
    #restart: always
    build: .
    ports:
       - '3000:3000'
    #volumes:
     # - /node_modules
      # make sure i add persistent later
    #environment
  redis: 
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /server/instance/db.sqlite
  backend:
    tty: true 
    # restart: always
    command: ["pip", "install",  "python-dotenv"]
    
    build: ./server
    ports:
     - "8000:8000"