version: '3'

services:
  frontend:
    build: 
      context: ./frontend
    tty: true
    ports:
      - '3000:3000' # Map local port for development; remove this for Cloud Run

  redis:
    image: redis
    ports:
      - "6379:6379" # Map local port for development; can be removed if using Memorystore

  backend:
    build:
      context: ./server  # Adjust the context to point to your backend directory
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - redis  # If using Redis in Cloud Run; change this if using Memorystore
    volumes:
      - ./server/instance:/backend/instance  # Mount SQLite database volume
