version: '3'

services:
  web:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - ./server:/server/server
    environment:
      - FLASK_ENV=development
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"