version: '3'
services:
  db:
    container_name: ecocat_db
    image: mongo
    ports:
      - "27017:27017"
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db